src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Cette adresse email est déjà utilisée, merci de la modifier"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseignez un pseudonyme")
     */
    private $alias;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Vous devez renseigner une adresse email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre mot de passe")
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Vous n'avez pas correctement comfirmé votre mot de passe")
     */
    private $passwordConfirm;

    /**
     * @ORM\Column(type="datetime", nullable=false)
     * @Assert\DateTime
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    public function __construct()
    {
        $this->userRoles = new ArrayCollection();
    }

    /**
     * initialize creation date
     *
     * @ORM\PrePersist
     */
    public function userCreatedAt()
    {
        if(empty($this->createdAt)) {
            $date = new DateTime('now');
            $this->createdAt = $date;
        }
    }

    /**
     * Used for Twig's purposes
     *
     * @return string
     */
    public function getFullName()
    {
        return "{$this->getLastName()} {$this->getFirstName()}";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    /**
     * @return string
     */
    public function getPasswordConfirm()
    {
        return $this->passwordConfirm;
    }

    /**
     * @param string $passwordConfirm
     */
    public function setPasswordConfirm($passwordConfirm): void
    {
        $this->passwordConfirm = $passwordConfirm;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     */
    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }



    /**
     * functions needed because of the interface
     */

    /**
     * Returns the roles granted to the user.
     */
      public function getRoles()
      {
          $roles = $this->userRoles->map(function($role){
              return $role->getTitle();
          })->toArray();

          $roles[] = 'ROLE_USER';

          return $roles;
      }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->getEmail();
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword()
    {
        return $this->getHash();
    }

    /**
     * getSalt is useless here because the salt is already in bcrypt.
     * eraseCredentials is useless too : we have not data to erase
     */

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt() {}

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles()
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }
}

templates/navbar/navbar.html.twig
{# navbar is available on all the website's pages #}
<div class="navbar-custom">
    <nav class="navbar navbar-expand-lg navbar-light">

        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mr-auto float-left">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('home') }}">Accueil<span class="sr-only">(current)</span></a>
                </li>

{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href="{{ path('home') }}">#}
{#                        <img class="img-fluid" src="{{ asset('/images/logo.jpg') }}" alt="">#}
{#                    </a>#}
{#                </li>#}

            </ul>
            <ul class="navbar-nav ml-auto float-right">
                {% if app.user %}
                    <li class="nav-item dropdown">

                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="accountDropdownLink">
                            <img src="{{ app.user.picture }}" class="avatar avatar-small" alt="Image de {{ app.user.fullName }}"> {{ app.user.fullname }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accountDropdownLink">
                            <a href="{{ path('account_index') }}" class="dropdown-item">Mon compte</a>
                            <a href="{{ path('account_profile') }}" class="dropdown-item">Mon profil</a>
                            <div class="dropdown-divider"></div>
                            <a href="{{ path('account_logout') }}" class="dropdown-item">Deconnexion</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{{ path('account_register') }}" class="nav-link">Créer un compte</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ path('account_login') }}" class="nav-link">Connexion</a>
                    </li>
                {%  endif %}
            </ul>
        </div>
    </nav>
</div>